//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        internal static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string Ekle {
            get {
                return ResourceManager.GetString("Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        internal static string Fiyat {
            get {
                return ResourceManager.GetString("Fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string GirişYap {
            get {
                return ResourceManager.GetString("GirişYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string Güncelle {
            get {
                return ResourceManager.GetString("Güncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        internal static string Kategori {
            get {
                return ResourceManager.GetString("Kategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Ad.
        /// </summary>
        internal static string KategoriAd {
            get {
                return ResourceManager.GetString("KategoriAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KategoriID.
        /// </summary>
        internal static string KategoriId {
            get {
                return ResourceManager.GetString("KategoriId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        internal static string KayıtOl {
            get {
                return ResourceManager.GetString("KayıtOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string KullanıcıAdı {
            get {
                return ResourceManager.GetString("KullanıcıAdı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KullanıcıID.
        /// </summary>
        internal static string KullanıcıId {
            get {
                return ResourceManager.GetString("KullanıcıId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri.
        /// </summary>
        internal static string Müşteri {
            get {
                return ResourceManager.GetString("Müşteri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Ad.
        /// </summary>
        internal static string MüşteriAd {
            get {
                return ResourceManager.GetString("MüşteriAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MüşteriID.
        /// </summary>
        internal static string MüşteriId {
            get {
                return ResourceManager.GetString("MüşteriId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Soyad.
        /// </summary>
        internal static string MüşteriSoyad {
            get {
                return ResourceManager.GetString("MüşteriSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        internal static string Soyad {
            get {
                return ResourceManager.GetString("Soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Takip.
        /// </summary>
        internal static string StokTakip {
            get {
                return ResourceManager.GetString("StokTakip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        internal static string Türkçe {
            get {
                return ResourceManager.GetString("Türkçe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kategori Ekle.
        /// </summary>
        internal static string YeniKategoriEkle {
            get {
                return ResourceManager.GetString("YeniKategoriEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kişi Ekle.
        /// </summary>
        internal static string YeniKişiEkle {
            get {
                return ResourceManager.GetString("YeniKişiEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Müşteri Ekle.
        /// </summary>
        internal static string YeniMüşteriEkle {
            get {
                return ResourceManager.GetString("YeniMüşteriEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ürün Ekle.
        /// </summary>
        internal static string YeniÜrünEkle {
            get {
                return ResourceManager.GetString("YeniÜrünEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇıkışYap.
        /// </summary>
        internal static string ÇıkışYap {
            get {
                return ResourceManager.GetString("ÇıkışYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        internal static string Ürün {
            get {
                return ResourceManager.GetString("Ürün", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Ad.
        /// </summary>
        internal static string ÜrünAd {
            get {
                return ResourceManager.GetString("ÜrünAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Fiyat.
        /// </summary>
        internal static string ÜrünFiyat {
            get {
                return ResourceManager.GetString("ÜrünFiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜrünID.
        /// </summary>
        internal static string ÜrünId {
            get {
                return ResourceManager.GetString("ÜrünId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kategori.
        /// </summary>
        internal static string ÜrünKategori {
            get {
                return ResourceManager.GetString("ÜrünKategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜyeOl.
        /// </summary>
        internal static string ÜyeOl {
            get {
                return ResourceManager.GetString("ÜyeOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        internal static string İngilizce {
            get {
                return ResourceManager.GetString("İngilizce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string Şifre {
            get {
                return ResourceManager.GetString("Şifre", resourceCulture);
            }
        }
    }
}
